# Generated by Django 5.0.2 on 2024-03-13 15:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("batizados", "0001_initial"),
        ("camarinhas", "0001_initial"),
        ("emergencias", "0001_initial"),
        ("enderecos", "0001_initial"),
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sobrenome", models.CharField(max_length=50)),
                ("data_de_nascimento", models.DateTimeField()),
                ("identidade", models.IntegerField(unique=True)),
                ("cpf", models.BigIntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=11)),
                ("profissao", models.CharField()),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("Pai de Santo", "Pai De Santo"),
                            ("Mãe de Santo", "Mae De Santo"),
                            ("Pai Pequeno", "Pai Pequeno"),
                            ("Mãe Pequena", "Mae Pequena"),
                            ("Iaô", "Iao"),
                            ("Ogã", "Ogan"),
                            ("Médium de Trabalho", "Medium De Trabalho"),
                            ("Médium em Desenvolvimento", "Medium Desenvolvimento"),
                        ],
                        default="Médium em Desenvolvimento",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("admin", models.BooleanField(blank=True, default=False, null=True)),
                ("amaci", models.BooleanField(blank=True, default=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batizado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batizados.batizado",
                    ),
                ),
                (
                    "camarinha",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="camarinhas.camarinha",
                    ),
                ),
                (
                    "contato_emergencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="emergencias.emergencia",
                    ),
                ),
                (
                    "endereco",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="enderecos.endereco",
                    ),
                ),
                (
                    "entidades",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.entidade",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
