# Generated by Django 5.0.2 on 2024-03-13 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orixas",
                    models.CharField(
                        choices=[
                            ("Iansã", "Iansa"),
                            ("Iemanjá", "Iemanja"),
                            ("Nanã", "Nana"),
                            ("Obaluaê", "Obaluae"),
                            ("Ogum", "Ogum"),
                            ("Oxaguiã", "Oxaguia"),
                            ("Oxalá", "Oxala"),
                            ("Oxalufã", "Oxalufa"),
                            ("Oxossi", "Oxossi"),
                            ("Oxum", "Oxum"),
                            ("Oxumare", "Oxumare"),
                            ("Xangô", "Xango"),
                        ],
                        default="Oxalá",
                    ),
                ),
                (
                    "caboclo_de_pena",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "caboclo_boiadeiro",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "preto_velho",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "encantados",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "povo_de_esquerda",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "criancas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("odu_da_testa", models.CharField()),
                ("odu_da_nuca", models.CharField()),
                ("odu_do_nascimento", models.CharField()),
                ("odu_adjunto", models.CharField()),
                ("odu_negativo", models.CharField()),
                ("odu_positivo", models.CharField()),
            ],
        ),
    ]
